name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v3
      name: Checkout repo
    -
      name: Set up Docker Build
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_PASS }}
    -
      name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    -
      name: Run Docker build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: agf127229/node-hello-world:${SHORT_SHA}
